import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:goldenkrill/goldenkrill.dart';

/// GK1 wire-codec conformance.
///
/// Drives the shared vectors through the Dart [CatalogCodec]. `gk1_vectors.json`
/// here is a byte copy of the canonical `../../conformance/gk1_vectors.json`,
/// vendored into the package so the test runs inside the flutter-only container
/// mount (the canonical sibling dir is not mounted, and the SDK and golden-krill are
/// separate repos). The vectors were generated by `conformance/generate_vectors.py`
/// from the authoritative server codec `golden-krill/web/apps/catalog/gk1.py`; if any
/// assert fails, the Dart codec has drifted from the frozen GK1 contract.

/// Canonical sha256 of `conformance/gk1_vectors.json` (recorded in
/// conformance/README.md). The vendored copy must hash to exactly this, so a
/// mis-transcribed or hand-edited copy fails loudly instead of silently passing.
const String _kCanonicalVectorSha256 =
    '8064704da42255c923cd0a041f2b9eff265a9339e059bbc997354e43ed81cbe6';

void main() {
  final vectorBytes = File('test/gk1_vectors.json').readAsBytesSync();
  final vectors = jsonDecode(utf8.decode(vectorBytes)) as Map<String, dynamic>;
  final cases = (vectors['cases'] as List).cast<Map<String, dynamic>>();

  test('vendored copy matches canonical sha256', () {
    expect(sha256.convert(vectorBytes).toString(), _kCanonicalVectorSha256);
  });

  test('vector file carries cases', () => expect(cases, isNotEmpty));

  group('GK1 conformance vector', () {
    for (final c in cases) {
      final name = c['name'] as String;
      final json = c['json'] as String;
      final gk1 = c['gk1'] as String;

      test('$name: decode(gk1) is byte-exact json', () {
        expect(CatalogCodec.decode(gk1), json);
      });

      test('$name: encode(json) is byte-exact gk1', () {
        expect(CatalogCodec.encode(json), gk1);
      });

      test('$name: decoded struct matches', () {
        expect(jsonDecode(CatalogCodec.decode(gk1)), c['decoded']);
      });
    }

    test('ads_fill: AdItem parses the additive fill + edge-colour slots', () {
      final c = cases.firstWhere((c) => c['name'] == 'ads_fill');
      final bundle = AdBundle.fromJson(jsonDecode(CatalogCodec.decode(c['gk1'] as String)) as Map<String, dynamic>);
      expect(bundle.ads.single.fill, 'contain');
      expect(bundle.ads.single.edgeColors, ['#FFFFFF', '#EEEEEE', '#DDDDDD', '#CCCCCC']);
      expect(bundle.own.single.isPhotographic, isTrue); // fill == "blur"
      expect(bundle.own.single.edgeColors.length, 4);
    });
  });
}
