#!/usr/bin/env python3
"""Generate the canonical GK1 conformance vector FROM the authoritative server codec
(golden-krill/web/apps/catalog/gk1.py), so the vector agrees with the server by construction.

Run with host python3 (stdlib only; gk1.py imports only base64):

    python3 golden-krill-sdk/conformance/generate_vectors.py

It writes golden-krill-sdk/conformance/gk1_vectors.json and prints the file's
sha256. After running: paste that sha256 into conformance/README.md and re-vendor
the per-port copies (conformance/verify.py checks they match). GK1 is frozen, so
this should only ever need re-running if the case list changes, never the codec.

The codec path defaults to the sibling-repo layout (golden-krill-sdk and golden-krill
both under mobile/). Override with GK1_CODEC=/path/to/gk1.py if your checkout differs.
"""
import hashlib
import importlib.util
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GK1_PATH = os.environ.get(
    "GK1_CODEC",
    os.path.normpath(os.path.join(HERE, "..", "..", "golden-krill", "web", "apps", "catalog", "gk1.py")),
)

ABOUT = (
    "Golden Krill GK1 wire-codec conformance vectors. The single anti-drift contract for "
    "every port (Dart, TS, C#, Swift, Kotlin) and the Python backend. Each case pins a known "
    "input JSON string to its exact GK1 blob and its decoded struct. A port passes if, for "
    "every case: decode(gk1) == json (byte-exact) AND encode(json) == gk1 (byte-exact). "
    "GENERATED by conformance/generate_vectors.py from golden-krill/web/apps/catalog/gk1.py; do "
    "not hand-edit. GK1 is frozen/eternal (add GK2 for new layouts, never repurpose GK1)."
)

CODEC = {
    "tag": "GK1.",
    "key_utf8": "pink-rorqual//golden-krill//v1",
    "algorithm": (
        "blob = \"GK1.\" + base64url( XOR(utf8(json), key) ). The key is cycled over the "
        "bytes; XOR is its own inverse (same routine encodes and decodes). base64url INCLUDES "
        "'=' padding. Decode also passes raw JSON through (a leading '{' or '[') for dev/test."
    ),
}

# (name, note, json) - the json strings are the exact canonical inputs.
CASES = [
    ("config",
     "Per-app /config payload (ServeConfig). Exercises bools, ints, a float, and an empty string.",
     '{"reserve_share":true,"reserve_one_in":4,"fallback_fill":true,"fill_own_ads":false,'
     '"house_cooldown_sec":240,"max_per_session":3,"own_ads_cooldown_min":5,'
     '"banner_rotation_sec":60,"rewarded_seconds":10,"ad_badge_chance":0.15,"badge_url":"",'
     '"banner_sdk_refresh":false}'),
    ("ads",
     "Two-tier /ads payload: a=cross-promo, o=own-studio, n=per-serve nonce. Ad rows are bare "
     "positional tuples [id, image, store].",
     '{"a":[[101,"https://cdn.example/ad/a1.webp","play"]],'
     '"o":[[202,"https://cdn.example/ad/o1.webp","appstore"]],"n":"7f3a9c2e"}'),
    ("ads_empty",
     "Zero-fill /ads: both tiers empty (the slot collapses to nothing).",
     '{"a":[],"o":[]}'),
    ("unicode",
     "Multibyte UTF-8 round-trip (image path + nonce) - pins identical UTF-8 handling across ports.",
     '{"a":[[303,"https://cdn.example/ad/föö-naïve-日本.webp","play"]],"o":[],"n":"ünïcödé"}'),
    ("ads_fill",
     "Ad rows with the additive creative-fill slots [id, image, store, fill, \"T,B,L,R\"]: "
     "fill is contain|cover|blur, then the sampled edge colours top,bottom,left,right. Older "
     "SDKs ignore the trailing slots; this pins the shape so every port parses it identically.",
     '{"a":[[101,"https://cdn.example/ad/a1.webp","play","contain","#FFFFFF,#EEEEEE,#DDDDDD,#CCCCCC"]],'
     '"o":[[202,"https://cdn.example/ad/o1.webp","appstore","blur","#101010,#101010,#101010,#101010"]],'
     '"n":"7f3a9c2e"}'),
    ("ads_test",
     "Test-mode /ads bundle (response to a test=1 request): the additive `t` tag marks it a "
     "TEST AD response. Synthetic id 0, the always-fill TEST AD image, and a DIRECT store link "
     "(not a /c click token, so a test tap is never counted). Older SDKs ignore the unknown "
     "`t` key; this pins the test-bundle shape so every port (incl. Unity) handles it identically.",
     '{"a":[[0,"https://a.golden-krill.com/api/v1/test-ad/banner.png","https://golden-krill.com/about"]],'
     '"o":[[0,"https://a.golden-krill.com/api/v1/test-ad/banner.png","https://golden-krill.com/about"]],'
     '"n":"testnonce","t":1}'),
]


def _load_codec(path):
    spec = importlib.util.spec_from_file_location("gk1", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def build(gk1):
    cases = []
    for name, note, js in CASES:
        blob = gk1.encode(js)
        if gk1.decode(blob) != js:
            raise SystemExit(f"round-trip failed for case {name}")
        cases.append({"name": name, "note": note, "json": js, "gk1": blob, "decoded": json.loads(js)})
    return {"_about": ABOUT, "codec": CODEC, "cases": cases}


def main():
    gk1 = _load_codec(GK1_PATH)
    doc = build(gk1)
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    out = os.path.join(HERE, "gk1_vectors.json")
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    print("wrote", out)
    print("sha256", sha)


if __name__ == "__main__":
    main()
